

Olá estudante!

Me chamo Rafael Meirelles e irei revisar o seu projeto hoje e em eventuais futuras submissões até que ele cumpra todos os requisitos para o aceite.
Conte comigo nessa jornada e não se preocupe se precisar ajustar alguns detalhes, é parte do processo e fundamental para que você exercite os conceitos que vem aprendendo e assim melhore a qualidade dos seus códigos e análises.

**Peço que mantenha e não altere os comentários que eu fizer por aqui para que possamos nos localizar posteriormente, ok?**

Mais uma coisa, vamos utilizar um código de cores para você entender os meus feedbacks no seu notebook. Funciona assim:


<div class="alert alert-danger">
<strong>Vermelho</strong>

Erro que precisa ser consertado, caso contrário, seu projeto não pode ser aceito

</div>

<div class="alert alert-warning">
<strong>Amarelo</strong>

Alerta de um erro não crítco, mas que pode ser corrigido para melhoria geral no seu código/análise

</div>

<div class="alert alert-success">
<strong>Verde</strong>

Elogios
</div>

<div class="alert alert-info">
<strong>Comentário do estudante</strong>

Use uma caixa azul como essa para eventuais comentários que você gostaria de fazer para mim.
</div>

<div class="alert alert-danger">
<strong>Comentário do revisor v1</strong>

Estamos no caminho certo com essa versão, mas retocar os pontos indicados abaixo nos fará chegar em um resultado ainda mais incrível.
    
Conte comigo para ajudá-lo (a) em qualquer questão que possa vir a ter! Lembre-se de usar as caixas azuis para se comunicar comigo.
    
Até breve.
</div>

### Iniciação
1. Importando bibliotecas
2. configurando conexão com o banco SQL
3. Analisando dados

In [2]:
# import libraries
import pandas as pd
from sqlalchemy import create_engine

In [3]:
db_config = {
 'user': 'practicum_student', # username
 'pwd': 'QnmDH8Sc2TQLvy2G3Vvh7', # password
 'host': 'yp-trainers-practicum.cluster-czs0gxyx2d8w.us-east-1.rds.amazonaws.com',
 'port': 5432, # connection port
 'db': 'data-analyst-final-project-db' # the name of the database
 }
connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(db_config['user'],
db_config['pwd'],
db_config['host'],
db_config['port'],
db_config['db'])
engine = create_engine(connection_string, connect_args={'sslmode':'require'})

In [4]:
query = """
SELECT *
FROM books
LIMIT 5;
"""

books = pd.read_sql(query, con=engine)
books

,book_id,author_id,title,num_pages,publication_date,publisher_id
0,1,546,'Salem's Lot,594,2005-11-01,93
1,2,465,1 000 Places to See Before You Die,992,2003-05-22,336
2,3,407,13 Little Blue Envelopes (Little Blue Envelope...,322,2010-12-21,135
3,4,82,1491: New Revelations of the Americas Before C...,541,2006-10-10,309
4,5,125,1776,386,2006-07-04,268

In [5]:
query = """
SELECT *
FROM authors
LIMIT 5;
"""
authors = pd.io.sql.read_sql(query, con = engine)
authors

   author_id                          author
0          1                      A.S. Byatt
1          2  Aesop/Laura Harris/Laura Gibbs
2          3                 Agatha Christie
3          4                   Alan Brennert
4          5        Alan Moore/David   Lloyd

In [6]:
query = """
SELECT *
FROM publishers
LIMIT 5;
"""
publishers = pd.io.sql.read_sql(query, con = engine)
publishers

   publisher_id                          publisher
0             1                                Ace
1             2                           Ace Book
2             3                          Ace Books
3             4                      Ace Hardcover
4             5  Addison Wesley Publishing Company

In [7]:
query = """
SELECT *
FROM ratings
LIMIT 5;
"""
ratings = pd.io.sql.read_sql(query, con = engine)
ratings

   rating_id  book_id       username  rating
0          1        1     ryanfranco       4
1          2        1  grantpatricia       2
2          3        1   brandtandrea       5
3          4        2       lorichen       3
4          5        2    mariokeller       2

In [8]:
query = """
SELECT *
FROM reviews
LIMIT 5;
"""
reviews = pd.io.sql.read_sql(query, con = engine)
reviews

,review_id,book_id,username,text
0,1,1,brandtandrea,Mention society tell send professor analysis. ...
1,2,1,ryanfranco,Foot glass pretty audience hit themselves. Amo...
2,3,2,lorichen,Listen treat keep worry. Miss husband tax but ...
3,4,3,johnsonamanda,Finally month interesting blue could nature cu...
4,5,3,scotttamara,Nation purpose heavy give wait song will. List...

# Verificando o número total de livros lançados após primeiro dia do ano de 2000

In [9]:
query = """
SELECT 
    COUNT(*) AS total_books_after_2000
FROM books
WHERE publication_date > '2000-01-01';
"""

pub_2000 = pd.read_sql(query, con=engine)
pub_2000

   total_books_after_2000
0                     819

In [10]:
# Tivemos 819 livros lançados apartir de 01-01-2000, bastante lançamentos para se ler durante a quarentena.

<div class="alert alert-success">
<strong>Comentário do revisor v1</strong>

A questão está correta!

</div>

# Verificando o número de avaliações e a classificação média para cada livro

In [11]:
query = """
SELECT
    b.book_id,
    b.title,
    COUNT(r.rating_id) AS total_rating,
    ROUND(AVG(r.rating), 2) AS avg_rating
FROM books b
LEFT JOIN ratings r ON b.book_id = r.book_id
GROUP BY b.book_id, b.title
ORDER BY total_rating DESC;
"""
books_avg_rating = pd.read_sql(query, con=engine)
books_avg_rating

,book_id,title,total_rating,avg_rating
0,948,Twilight (Twilight #1),160,3.66
1,750,The Hobbit or There and Back Again,88,4.13
2,673,The Catcher in the Rye,86,3.83
3,75,Angels & Demons (Robert Langdon #1),84,3.68
4,302,Harry Potter and the Prisoner of Azkaban (Harr...,82,4.41
...,...,...,...,...
995,465,Naked Empire (Sword of Truth #8),2,3.50
996,55,A Woman of Substance (Emma Harte Saga #1),2,5.00
997,652,The Body in the Library (Miss Marple #3),2,4.50
998,790,The Magicians' Guild (Black Magician Trilogy #1),2,3.50
999,191,Disney's Beauty and the Beast (A Little Golden...,1,4.00

In [12]:
# Podemos notar o dobro de avaliações para o livro Crepúsculo, que se manteve com uma boa avaliação média

<div class="alert alert-success">
<strong>Comentário do revisor v1</strong>

A questão está correta!

</div>

# Editoria que lançou o maior número de livros com mais de 50 páginas

In [13]:
query ="""
SELECT
    p.publisher,
    COUNT(b.book_id) AS total_books
FROM books b
JOIN publishers p ON b.publisher_id = p.publisher_id
WHERE b.num_pages > 50
GROUP BY p.publisher
ORDER BY total_books DESC;
"""
filtered_publisher = pd.read_sql(query, con=engine)
filtered_publisher

                                             publisher  total_books
0                                        Penguin Books           42
1                                              Vintage           31
2                             Grand Central Publishing           25
3                                     Penguin Classics           24
4                                     Ballantine Books           19
..                                                 ...          ...
329                                         Turtleback            1
330  Atheneum Books for Young Readers: Richard Jack...            1
331                                     Penguin Signet            1
332                                    Victor Gollancz            1
333                      Harvard Business Review Press            1

[334 rows x 2 columns]

In [14]:
# Penguin books, lançaram 42 livros e foi a editora com maior número de lançamentos.

<div class="alert alert-success">
<strong>Comentário do revisor v1</strong>

A questão está correta!

</div>

# Autor com a média mais alta de classificações com pelo menos 50 avaliações

In [15]:
query = """
WITH filtered_publisher AS (
    SELECT
        b.book_id,
        b.author_id,
        AVG(r.rating) AS avg_rating,
        COUNT(r.rating_id) AS total_ratings
    FROM books b
    JOIN ratings r ON b.book_id = r.book_id
    GROUP BY b.book_id, b.author_id
    HAVING COUNT(r.rating_id) >= 50
)
SELECT
    a.author,
    ROUND(AVG(b50.avg_rating), 2) AS author_avg_rating
FROM filtered_publisher b50
JOIN authors a ON b50.author_id = a.author_id
GROUP BY a.author
ORDER BY author_avg_rating DESC
LIMIT 1;
"""
df_top_author = pd.read_sql(query, con=engine)
df_top_author

                       author  author_avg_rating
0  J.K. Rowling/Mary GrandPré               4.28

In [16]:
# J.K Rowling, tem a melhor avaliação entre os autores 4.28 de 5.0, mais 10 pontos para Grifinória!

<div class="alert alert-success">
<strong>Comentário do revisor v1</strong>

A questão está correta!

</div>

# Verificando o número médio de avaliações entre os usuários que classificaram mais do que 50 livros

In [18]:
query = """
WITH active_users AS (
    SELECT
        username
    FROM ratings
    GROUP BY username
    HAVING COUNT(DISTINCT book_id) > 50
),
user_reviews AS (
    SELECT
        r.username,
        COUNT(rv.review_id) AS total_reviews
    FROM active_users r
    LEFT JOIN reviews rv ON r.username = rv.username
    GROUP BY r.username
)
SELECT
    ROUND(AVG(total_reviews), 2) AS avg_reviews_per_user
FROM user_reviews;
"""

df_avg_user_reviews = pd.read_sql(query, con=engine)
df_avg_user_reviews

   avg_reviews_per_user
0                 24.33

In [19]:
# Vemos a média de avaliações entre os usuários que classificaram mais de 50 livros é de cerca de 24 livros!



<div class="alert alert-danger">
<strong>Comentário do revisor</strong>

Quase isso!
    
Aqui precisamos usar duas tabelas: `ratings` e `reviews`.
    
Primeiro precisamos identificar os usuários que classificaram mais de 50 livros, usando a tabela `ratings`.
    
Depois, **a partir desses usuários**, precisamos **contar** o número médio de avaliações, usando a tabela `reviews`. Ou seja, devemos refazer essa última query considerando apenas os usuários filtrados na anterior.
    
Com essa dica, acredito que seja possível para você escrever uma _query_ que irá atender perfeitamente à solicitação do projeto.

</div>


<div class="alert alert-success">
<strong>Comentário do revisor v2</strong>

Obrigado pelo ajuste!
</div>